import Image from "next/image";
import { navigation, projects, principles, toolbox, supporters, communities } from "@/content/site";

const ExternalLink = ({ href, children }: { href: string; children: React.ReactNode }) => <a href={href} target="_blank" rel="noreferrer">{children}<span aria-hidden="true"> ↗</span></a>;

function Header() { return <header className="site-header"><a className="wordmark" href="#index">TN<span>.</span></a><nav aria-label="Primary navigation">{navigation.map((item) => <a key={item.href} href={item.href}>{item.label}</a>)}</nav></header>; }

export default function Home() {
  return <><a className="skip-link" href="#main-content">Skip to content</a><Header /><main id="main-content">
    <section id="index" className="hero section-wrap" aria-labelledby="hero-title"><div className="hero-copy"><p className="eyebrow">TRUENINE / ENGINEER &amp; ACCESSIBILITY ADVOCATE</p><h1 id="hero-title">Build thoughtfully.<br /><em>Share openly.</em></h1><p className="hero-intro">I&apos;m TrueNine, a full-stack developer from China building reusable developer tooling, AI-assisted engineering workflows, and software that works for more people.</p><a className="text-link" href="#projects">Explore the work <span aria-hidden="true">↓</span></a></div><div className="hero-aside"><div className="portrait-frame"><Image src="/personal_photo.jpeg" alt="Portrait of TrueNine" fill priority sizes="(max-width: 700px) 80vw, 34vw" /></div><p className="caption">Writing code with NVDA and Windows Magnifier.<br />Accessibility is part of the architecture.</p></div></section>
    <section id="projects" className="section-wrap section" aria-labelledby="projects-title"><div className="section-heading"><p className="eyebrow">01 / SELECTED WORK</p><h2 id="projects-title">Featured projects</h2><p>Small, focused tools for teams that care about the details.</p></div><div className="project-list">{projects.map((project, index) => <article className="project-row" key={project.name}><div className={`project-mark ${project.tone}`}><span>0{index + 1}</span></div><div className="project-content"><h3>{project.name}</h3><p>{project.description}</p><ul className="tag-list">{project.stack.map((tag) => <li key={tag}>{tag}</li>)}</ul></div><ExternalLink href={project.href}>View project</ExternalLink></article>)}</div></section>
    <section id="principles" className="section-wrap section split-section" aria-labelledby="principles-title"><div className="section-heading"><p className="eyebrow">02 / NOTES TO SELF</p><h2 id="principles-title">What I care about</h2></div><div className="principles-list">{principles.map(([number, title, text]) => <div className="principle" key={number}><span className="principle-number">{number}</span><div><h3>{title}</h3><p>{text}</p></div></div>)}</div></section>
    <section id="toolbox" className="section-wrap section split-section toolbox-section" aria-labelledby="toolbox-title"><div className="section-heading"><p className="eyebrow">03 / THE TOOLBOX</p><h2 id="toolbox-title">Tools I reach for</h2></div><div className="toolbox-grid">{toolbox.map(([group, ...items]) => <div className="toolbox-group" key={group}><h3>{group}</h3><ul>{items.map((item) => <li key={item}>{item}</li>)}</ul></div>)}</div></section>
    <section id="acknowledgments" className="section-wrap section split-section" aria-labelledby="ack-title"><div className="section-heading"><p className="eyebrow">04 / THANKS</p><h2 id="ack-title">Acknowledgments</h2></div><div className="ack-content"><p>No open-source journey is a solo effort. I&apos;m grateful to the friends, mentors, developers, and communities whose work keeps the path open.</p><div className="link-columns"><div><h3>Supporters</h3><ul>{supporters.map((item) => <li key={item.label}><ExternalLink href={item.href}>{item.label}</ExternalLink></li>)}</ul></div><div><h3>Open-source communities</h3><ul>{communities.map((item) => <li key={item.label}><ExternalLink href={item.href}>{item.label}</ExternalLink></li>)}</ul></div></div></div></section>
    <section id="support" className="section-wrap section support-section" aria-labelledby="support-title"><div><p className="eyebrow">05 / KEEP IN TOUCH</p><h2 id="support-title">Support the work</h2><p>Stars, thoughtful feedback, documentation improvements, and project recommendations are equally welcome.</p><ExternalLink href="https://github.com/TrueNine">Find me on GitHub</ExternalLink></div><div className="support-card"><Image src="/alipay_qrcode.jpg" alt="Alipay QR code for supporting TrueNine" width={180} height={180} sizes="180px" /><p>Scan to support via Alipay.</p></div></section>
  </main><footer className="site-footer section-wrap"><span>© {new Date().getFullYear()} TrueNine</span><span>Build thoughtfully. Share openly.</span><a href="#index">Back to top ↑</a></footer></>;
}
